_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 45abe319-f577-48f3-86c7-a0925115075a
name: univ-sanfran-events
mail: mjuarez2@usfca.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/11
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
